services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    container_name: fastapi_service
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - DEVELOPMENT_MODE=false
      - AI_PROVIDER=ollama
      - OLLAMA_URL=http://ollama:11434
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./app
          target: /app
        - action: rebuild
          path: requirements.txt

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: streamlit_service
    ports:
      - "8501:8501"
    depends_on:
      - fastapi
    environment:
      - PYTHONUNBUFFERED=1
      - API_URL=http://fastapi:8000
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./app
          target: /app
        - action: rebuild
          path: requirements.txt

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - fastapi

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus

  ollama:
    image: ollama/ollama
    container_name: ollama_service
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    restart: unless-stopped

volumes:
  grafana-storage:
  ollama-data:
