FROM python:3.11-slim

# Env vars
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    STREAMLIT_PORT=8501

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Streamlit config
RUN mkdir -p /root/.streamlit && \
    echo "[server]\n\
    enableCORS = false\n\
    enableXsrfProtection = false\n\
    " > /root/.streamlit/config.toml

EXPOSE $STREAMLIT_PORT

CMD ["streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]
